### ISSUE TITLE
Allow overriding session duration per primary role

### ISSUE THREAD

**Issue by MichaelPalmer1** [GESkunkworks/gossamer3#40]
Some users need to login to multiple roles in `bulk-login` where the session duration for one role may be higher than another. Allow this to be configured in their bulk role config file:

```yaml
roles:
  - primary_role_arn: arn:aws:iam:111122223333:role/developer
    session_duration: 7200
  - primary_role_arn: arn:aws:iam:22223333444:role/developer
    # uses default session duration from IDP config
```
